const letters = [
  `💌 1. My First Friend – My Forever Buddy\nDear Piyu,\nFrom the very beginning, you were my first ever best friend.\nYou’ve seen me cry, laugh, fail, succeed—and loved me anyway.\nEvery memory of us growing up is a golden treasure in my heart.\nYou were always the stronger one, guiding me without even knowing it.\nYour laughter used to echo through the house and heal every sadness.\nI still remember how we played, fought, made up, and grew stronger.\nYou’re not just my sister—you’re my second soul.\nNo one in the world understands me like you do.\nAnd today, on your birthday, I just want to say—thank you for existing.\nI love you more than words will ever be able to explain.`,

  `💌 2. You Are My Home\nDear Piyu,\nSome people are places—and you’re my favorite one.\nBeing with you feels like being wrapped in peace.\nNo matter how much the world changes, your love stays the same.\nYou listen like no one else, love with your whole heart.\nYou never let me feel alone, not even for a moment.\nYour arms are the safest place I know.\nYou have always been my soft landing after a hard day.\nYou’ve never failed to remind me of who I truly am.\nYou are not just a sister—you are my home in human form.\nHappy birthday to my living miracle.`,

  `💌 3. My Silent Warrior\nDear Piyu,\nYou never brag, never boast—but I’ve seen your strength.\nYou’ve faced storms with a calm face and a strong heart.\nYou carry others even when you're breaking inside.\nYou’re a warrior wrapped in kindness and silence.\nYou protect without shouting, support without conditions.\nI’ve watched you rise after every fall with grace.\nYou inspire me without even trying.\nYou make bravery look gentle and sweet.\nYou’ve fought life like a true queen, without losing your smile.\nOn your birthday, I honour the fighter in you.`,

  `💌 4. The Brightest Light in My Life\nDear Piyu,\nThere’s a light in you that never goes out.\nEven on my darkest days, your presence is my sun.\nYou shine so effortlessly, lighting up every room you walk into.\nYour energy is soft, warm, and full of life.\nYou’ve taught me how to find joy in little things.\nYou bring laughter into boring days and peace into stressful ones.\nEven your silence speaks volumes of love.\nYou don’t just light up candles—you light up lives.\nI’m blessed to walk this life with someone who glows like you.\nHappy birthday to the brightest soul I know.`,

  `💌 5. P For Piyu, P For Perfect\nDear Piyu,\nIf I had to describe you in one word—it would be "complete."\nYou’re calm and chaos, soft and strong, sweet and spicy.\nYou balance everyone around you like magic.\nYou’re always the one holding the family together.\nYou give without expecting and love without limits.\nYour name may be short, but your love is infinite.\nThe way you care makes everyone feel special.\nYou don’t just exist—you add value wherever you go.\nAnd today, we celebrate the gift that is YOU.\nP for Piyu. P for Pure Perfection.`,

  `💌 6. The Queen of Hearts\nDear Piyu,\nYou don’t wear a crown, yet you rule hearts effortlessly.\nYou don’t need a throne—your kindness makes you royal.\nYou lead with compassion, never with pride.\nEvery person who meets you leaves with a smile.\nYou don’t just change moods, you change lives.\nYou’re loved not just because you're good—but because you're genuine.\nIn your world, even broken people feel seen.\nI’m so proud to be your sibling.\nToday, the Queen celebrates her birthday—and I, your loyal subject, salute you!\nMay your reign of love and light continue forever.`,

  `💌 7. My Constant\nDear Piyu,\nWhen everything changed, you stayed.\nWhen I was lost, you found me.\nWhen I doubted myself, you believed in me harder.\nYou’ve been my strongest pillar—unmoving, unshaken.\nOthers came and left, but you never even stepped back.\nYou were my reminder that love doesn’t give up.\nYou’ve been my diary, my mirror, my anchor.\nYou’ve held me together when I didn’t know I was falling apart.\nYou’ve loved me in silence and celebrated me loudly.\nThank you for being my forever constant. Happy birthday.`,

  `💌 8. The Laugh That Heals\nDear Piyu,\nYour laugh is pure magic.\nIt has a way of fixing things no words ever could.\nIt makes even bad days feel beautiful.\nSometimes, I wait just to hear you laugh again.\nIt's not just a sound—it's a feeling, a blessing.\nYou carry so much light, even in your giggles.\nThank you for always sharing that joy with me.\nI hope today, your heart laughs louder than ever before.\nKeep laughing, keep healing us all.\nHappy Birthday to the girl whose laughter is a cure.`,

  `💌 9. You Make Ordinary Moments Special\nDear Piyu,\nWith you, even a boring day becomes memorable.\nWhether we’re sitting quietly or dancing like crazy, it feels magical.\nYou’ve made me fall in love with small things.\nA chai moment. A walk. A hug. A meme.\nYou find happiness in simplicity—and that’s your gift.\nLife feels fuller, lighter, and better with you around.\nYou’ve taught me that joy is not in events but in people.\nAnd you are my joy.\nHere’s to a life filled with your kind of magic.\nHappy Birthday, magician of hearts.`,

  `💌 10. The Artist of Love\nDear Piyu,\nYou paint people’s lives with love.\nYour words, your hugs, even your scoldings—they all carry care.\nYou notice what others miss.\nYou remember little things and turn them into beautiful memories.\nYou give more than anyone ever asks.\nYour love is not loud—but it’s lasting.\nYou are love in its purest form.\nAnyone loved by you is truly lucky.\nOn your birthday, I hope you feel the love you give multiplied back to you.\nYou deserve nothing less.`,

  `💌 11. My Favorite Chapter\nDear Piyu,\nIf my life were a book, you’d be my favorite chapter.\nThe part I’d read again and again—smiling, crying, feeling.\nThe story gets interesting the moment you enter.\nYou’ve added meaning to my journey in a way no one else has.\nYour name feels like a hug when I write it.\nYour presence is the most powerful plot twist I never knew I needed.\nYou are not just a character—you are the heart of my story.\nHappy birthday to the most beautiful chapter in my life.`,

  `💌 12. You Deserve the World\nDear Piyu,\nIf I could, I’d gift you the stars tonight.\nYou deserve every good thing this universe has to offer.\nYou deserve love that makes you glow.\nFriends that feel like family.\nDreams that come true.\nAnd peace that stays forever.\nYou’ve spent your whole life giving.\nNow it’s your turn to receive—limitlessly.\nI pray this year brings you everything your heart has ever whispered.\nHappy Birthday, universe’s favorite.`,

  `💌 13. You Are My Reflection\nDear Piyu,\nIn you, I see parts of myself.\nMy best parts. My forgotten parts. My hopeful parts.\nWhen I look at you, I’m reminded of who I can be.\nYou reflect strength, softness, and silent power.\nYou remind me of the love we were born into.\nOf the journey we share.\nWe’re two hearts, shaped from the same stars.\nAnd I couldn’t have asked for a better reflection.\nHappy birthday, mirror of my soul.`,

  `💌 14. The One I Look Up To\nDear Piyu,\nYou may not know this, but I look up to you—always have.\nYour courage, your heart, your dreams… they inspire me.\nYou’ve handled life’s struggles with such quiet dignity.\nYou’ve shown me how to grow through pain.\nYou’ve taught me how to stay gentle in a tough world.\nYou're not just older by age—you're wiser by soul.\nAnd I’m proud to call you my guiding star.\nHappy birthday, role model and soul guide.`,

  `💌 15. My Soul’s Twin\nDear Piyu,\nWe may not be twins by birth, but we are in spirit.\nYou feel my moods before I say a word.\nYou read my silence like it’s loud music.\nWe share a connection that’s beyond blood.\nWe are tied by heartstrings that don’t break.\nI’ve laughed the most with you.\nI’ve healed the most with you.\nI’ve lived the most with you.\nYou are the other half of my heartbeat.\nHappy birthday to my soul twin.`,

  `💌 16. A Hug in Words\nDear Piyu,\nIf I could wrap all my feelings for you in a single moment, it would be a hug.\nThe kind that holds your heart and never lets go.\nThis letter is that hug.\nFor the days you feel tired, lost, or unseen.\nFor the days you cry and no one notices—I do.\nYou don’t have to say anything; I understand it all.\nEven when the world misunderstands you—I never will.\nYou’ve always been my soft place to land.\nNow, let me be yours.\nHappy birthday—sending you this forever hug.`,

  `💌 17. The Girl with the Golden Soul\nDear Piyu,\nIf hearts were visible, yours would shine the brightest.\nGolden, glowing, generous beyond imagination.\nYou give without limits, care without condition.\nYou make others feel seen, heard, and valued.\nYour kindness is your power, and your soul is your crown.\nI’ve seen you stay kind even to those who didn’t deserve it.\nI hope the world returns your love tenfold.\nBecause you, my golden girl, are rare and irreplaceable.\nHappy birthday to the heart of gold.`,

  `💌 18. My Favorite Memory Maker\nDear Piyu,\nEvery memory with you is like a polaroid in my heart.\nFrom midnight snacks to deep talks under the sky…\nFrom our little fights to our big laughs…\nYou make every moment unforgettable.\nEven ordinary days become magical with you around.\nYou’re not just a memory—you’re the reason they matter.\nLet’s keep making more, forever.\nBecause life is better with you in every frame.\nHappy birthday, memory maker.`,

  `💌 19. You’re Not Just Loved – You’re Celebrated\nDear Piyu,\nI don’t just love you—I celebrate you.\nEvery little thing about you deserves fireworks.\nYour laughter, your tears, your strength, your softness.\nYou’ve touched lives just by being you.\nYou are not someone who blends into the background—you shine.\nEven when no one claps, you still dance.\nAnd today, I hope the whole world claps for you.\nBecause you’re not just a blessing—you’re a celebration.\nHappy birthday to the light that never dims.`,

  `💌 20. The Heartbeat of Our Family\nDear Piyu,\nYou are the heartbeat that keeps us all connected.\nYou hold us together with invisible threads of love.\nYou carry burdens without letting anyone know.\nYou smile even when your own heart is tired.\nYou make this family feel like home.\nWithout you, we’d all be scattered pieces.\nYou bring warmth, peace, and endless understanding.\nThank you for being the quiet force that keeps us whole.\nHappy birthday to our family’s heart.`,

  `💌 21. The Sister I’d Choose Again and Again\nDear Piyu,\nEven if I had a million choices, I’d still choose you.\nEvery single time.\nThrough all our ups and downs, one thing has never changed—my love for you.\nYou’re not just my sister by blood—you’re my sister by soul.\nYou’ve been my cheerleader, therapist, partner in crime.\nYou’ve seen me at my worst and still called me worthy.\nYou’ve shown me what unconditional love looks like.\nAnd if life gave me another chance—I’d choose you, again.\nHappy birthday to the one I’ll always choose.`,

  `💌 22. For Everything You Are\nDear Piyu,\nToday’s letter isn’t just about one thing—it’s for everything you are.\nFor the love you give, the strength you carry.\nFor your dreams, your flaws, your beauty, your fire.\nFor the sister, daughter, friend, and queen you are.\nYou are not meant to be compared—you are meant to be celebrated.\nI hope this birthday reminds you how incredibly precious you are.\nNot just today—but every single day.\nYou are a blessing. You are a light. You are deeply, deeply loved.\nHappy birthday, my everything.`
];

const container = document.getElementById('letters-container');
letters.forEach((text, i) => {
  const btn = document.createElement('button');
  btn.innerText = `Letter ${i + 1}`;
  btn.onclick = () => openModal(text);
  container.appendChild(btn);
});

function openModal(content) {
  document.getElementById('messageText').innerText = content;
  document.getElementById('messageModal').style.display = 'block';
}

function closeModal() {
  document.getElementById('messageModal').style.display = 'none';
}
